.gitignore
README.md

Contributes to #13 .
Started down the path of building wheels, but decided to pause and instead focus on moving more code out of the shell scripts and into Python.
This PR just includes some small docs changes.

add more links, update gitignore

---

.github/ISSUE_TEMPLATE/new-check.yml
README.md

Contributes to #48 .
Adds an issue form for requesting a new check.

[docs] add issue form for new checks

---

.github/ISSUE_TEMPLATE/new-check.yml

Contributes to #48 .
Makes some minor changes to the template for documenting new checks, based on my experience writing #51 .

[docs] clean up issue forms

---

.github/ISSUE_TEMPLATE/bug-report.yml

Contributes to #48.
Adds a template for reporting bugs.

[docs] add template for reporting bugs

---

pyproject.toml
src/pydistcheck/__init__.py
src/pydistcheck/_compat.py
src/pydistcheck/checks.py
src/pydistcheck/cli.py
src/pydistcheck/distribution_summary.py
src/pydistcheck/utils.py

Contributes to #21.
Resolves the following warnings from `pylint`.
> src/pydistcheck/checks.py:1:0: C0114: Missing module docstring (missing-module-docstring)
src/pydistcheck/__init__.py:1:0: C0114: Missing module docstring (missing-module-docstring)
src/pydistcheck/cli.py:1:0: C0114: Missing module docstring (missing-module-docstring)
src/pydistcheck/utils.py:1:0: C0114: Missing module docstring (missing-module-docstring)
src/pydistcheck/utils.py:22:4: C0116: Missing function or method docstring (missing-function-docstring)
src/pydistcheck/utils.py:27:4: C0116: Missing function or method docstring (missing-function-docstring)
src/pydistcheck/utils.py:31:4: C0116: Missing function or method docstring (missing-function-docstring)
src/pydistcheck/distribution_summary.py:1:0: C0114: Missing …

resolve pylint warnings: docstrings

---

Makefile
pyproject.toml

build source distro and wheels locally

---

.github/workflows/manual-run.yml
.github/workflows/smoke-tests.yml
Makefile

[ci] fix manually-trigggered CI runs (fixes #119)

---

bin/get-release-files.py
bin/run-smoke-tests.sh

Adds a few more packages to the smoke tests.
See comments in the diff for why I chose these particular packages.

[ci] add more packages to smoke-tests

---

README.md

[docs] add quickstart to README

---

.github/workflows/smoke-tests.yml

First step towards testing the proposal from https://github.com/orgs/community/discussions/26733#discussioncomment-3253155.

[ci] test re-actors/alls-green GitHub Actions check

---

.github/workflows/smoke-tests.yml

Testing the proposal in https://github.com/orgs/community/discussions/26733#discussioncomment-3253155.

[ci] test failing smoke-tests

---

Makefile
bin/check-test-packages.sh
tests/test_distribution_summary.py

This is a minor just-moving-code-around PR, cleaning up things I noticed while working on #141 .

[ci] minor test restructuring

---

CONTRIBUTING.md
pyproject.toml
src/pydistcheck/__init__.py
src/pydistcheck/cli.py
tests/test_cli.py

Fixes #173.
Adds a `--version`.
```shell
pydistcheck --version
```

add --version (fixes #173)

---

.github/workflows/build-and-publish-wheels.yml
.github/workflows/check-docs.yml
.github/workflows/manual-run.yml
.github/workflows/smoke-tests.yml
.github/workflows/static-analysis.yml
.github/workflows/unit-tests.yml

Updates all the GitHub Actions used in the project to their latest version.

[ci] update to latest version of third-party GitHub Actions

---

.github/workflows/build-and-publish-wheels.yml
.github/workflows/unit-tests.yml

Updates to newer versions of GitHub Actions.

[ci] update versions of GitHub Actions

---

src/pydistcheck/__init__.py

Putting up a release to get this fix out: #205

release v0.5.2

---

.github/workflows/build-and-publish-wheels.yml

[ci] fix download-artifact use in package uploads

---

CONTRIBUTING.md
bin/create-release-pr
bin/create-version-bump-pr
src/pydistcheck/__init__.py

release v0.6.0
Also adds some scripts for creating these release PRs, and updates the corresponding docs.

release v0.6.0

---

src/pydistcheck/__init__.py

bump development version

---

.github/workflows/check-docs.yml
.github/workflows/smoke-tests.yml
.github/workflows/unit-tests.yml
docs/_static/defaults.toml
docs/configuration.rst
docs/env.yml
src/pydistcheck/cli.py

Contribute sto #233.
Updates docs on configuration options.

[docs] update docs on configuration

---

docs/check-reference.rst

Fixes #188
Adds a bit more detail and some external links to the Check Reference.

[docs] add links and detail to Check Reference

---

src/pydistcheck/__init__.py

release v0.7.0

---

.pre-commit-config.yaml
pyproject.toml
tests/test_config.py

Adds `flake8-fixme` checks to `ruff` config.

add flake8-fixme checks

---

.github/CODE_OF_CONDUCT.md
.pre-commit-config.yaml
docs/how-to-test-a-python-distribution.rst
src/pydistcheck/distribution_summary.py

* adds typo-checking with `codespell` in pre-commit config
* updates all pre-commit hooks to their latest versions
Happy to say it caught a few things!

[ci] add codespell

---

.pre-commit-config.yaml
src/pydistcheck/_utils.py
tests/test_cli.py
tests/test_utils.py

Fixes #300
Also updates all `pre-commit` hooks to their latest versions, via `pre-commit autoupdate`.

fix parsing of unit strings with 2 letters (fixes #300)

---

CONTRIBUTING.md
src/pydistcheck/__init__.py

release v0.9.0

---

src/pydistcheck/__init__.py

release v0.9.1

---

.pre-commit-config.yaml
docs/how-to-test-a-python-distribution.rst

Fixes #299
Adds link to documentation for a bunch of tools for working with object files.

[docs] add docs on more tools for checking distributions

---

docs/how-to-test-a-python-distribution.rst

Follow-up to #316 
Implements @agriyakhetarpal 's suggestions from https://github.com/jameslamb/pydistcheck/pull/316#issuecomment-2774399740
And adds a few more tools I thought of that can be used to inspect shared libraries.

[docs] add more tools to docs
