jameslamb/pydistcheck

Makefile, README.md, requirements.txt, setup.cfg, src/py_artifact_linter/__init__.py, src/py_artifact_linter/cli.py
Contributes to #13.
Adds the scaffolding for exposing this project as a `click` CLI.
Also changes `make install` to use `pipx` instead of `pip` so that development doesn't mess with my local environment.
These tutorials were helpful in setting this up:
* https://click.palletsprojects.com/en/7.x/commands/#callback-invocation
* https://setuptools.pypa.io/en/latest/userguide/entry_point.html
=> set up CLI

requirements.txt, src/py_artifact_linter/__init__.py
Contributes to #13 .
Some simple `pandas` code was added as a placeholder. in the first PR setting up the CLI (#18).
That code is no longer necessary, and this PR removes it.
=> remove testing-only code in CLI

pyproject.toml, requirements.txt, src/py_artifact_linter/_compat.py, src/py_artifact_linter/cli.py
Fixes #24.
Adds preliminary support for parsing options from `pyproject.toml`. The project doesn't currently have any configuration that needs that, but such changes are coming.
```shell
make build install
py-artifact-linter check --file yeah
```
=> get options from pyproject.toml (fixes #24)

pyproject.toml, src/py_artifact_linter/cli.py, src/py_artifact_linter/distribution_summary.py
Sets the line length for `black` explicitly, and to 100 characters.
It's personal preference. I get to pick so 😜 .
Also this shows an example of configuring something other than the build system in `pyproject.toml`, which is cool (for some definition of cool).
=> [ci] set black line length to 100

.github/workflows/check-docs.yml, .gitignore, .readthedocs.yaml, docs/Makefile, docs/conf.py, docs/env.yml, docs/index.rst
Fixes #31.
Sets up the structure of a documentation site.
Also adds a CI job building the docs.
Used `sphinx-quickstart`, following https://www.sphinx-doc.org/en/master/usage/quickstart.html.
Added automatic builds of `main` at https://readthedocs.org/projects/pydistcheck.
=> [docs] set up readthedocs site (fixes #31)

.github/workflows/smoke-tests.yml, .github/workflows/static-analysis.yml, .gitignore, Makefile
* makes `static-analysis` a standalone GitHub Actions workflows
* expands smoke tests to run on Linux, Mac, and Windows
=> [ci] split up CI jobs, run smoke tests on multiple OSes

.github/workflows/smoke-tests.yml, .github/workflows/unit-tests.yml
Follow-up to #36 .
GitHub branch protections allow blocking merges until certain GitHub Actions jobs pass.
Unfortunately, the logic for that relies on job *names*.
This project's CI job names include information like the version of Python.
As new versions of Python are released and older ones reach end-of-life, that set of job names will change.
This PR adds "all successful" jobs that will only pass if all other jobs in a given workflow succeed, to avoid needing to manually update the list of passing tests whenever the set of CI jobs changes.
=> add summary CI jobs for branch protections

.github/release-drafter.yml, .github/workflows/release-drafter.yml
Contributes to #39.
Sets up https://github.com/release-drafter/release-drafter, to automatically generate release notes each time a new GitHub release is cut.
=> [ci] enable release-drafter

.github/workflows/smoke-tests.yml
This project's smoke tests take longer to run than its unit tests.
The Windows and macOS smoke tests are slower than the Linux tests, and therefore end up determining how long it takes for a PR to be mergeable.
Now that unit tests covering Linux, Windows, and macOS have been added (#30), I don't think it's necessary to run the smoke tests on 3 operating systems.
This PR proposes limiting the smoke tests to just Linux, to reduce CI time.
=> [ci] limit smoke tests to Linux

.github/workflows/build-and-publish-wheels.yml, setup.cfg
Contributes to #39.
Adds a GitHub Actions job that builds wheels with `cibuildwheel` and pushes them to PyPI.
Based on https://github.com/pypa/cibuildwheel/blob/0117165b02675521b3db2d05033747819bb3ecc5/examples/github-deploy.yml.
=> [ci] start publishing wheels

.github/workflows/build-and-publish-wheels.yml
Contributes to #39.
Adds a task to upload source distribution + wheel(s) to GitHub releases page whenever a GitHub release is created.
https://github.com/svenstaro/upload-release-action
=> [ci] automatically upload distributions to release

docs/check-reference.rst, docs/index.rst, src/pydistcheck/checks.py
Contributes to #14.
Contributes to #46.
Adds a page to the documentation that contains a long-form description of each issue that `pydistcheck` checks for.
Adds a short description to the docs home page.
=> [docs] add Check reference to docs

.github/ISSUE_TEMPLATE/new-check.yml
follow-up to #49 
I think all the issue template prompts should be in active voice, like "request a new check", "report a bug", etc.
=> [docs] make template active-voice

.github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/new-check.yml
Fixes #48.
Adds a template for feature requests that are anything other than "please add this check".
Also cleans up some miscellaneous stuff in the template for requesting a new check.
=> [docs] add template for feature requests (fixes #48)

src/pydistcheck/distribution_summary.py
`_DistributionSummary.from_file()` is a classmethod, but it current has `self` in its signature and re-uses `_DistributionSummary` instead of the passed-in class.
That is non-standard in Python development and could be confusing for contributors.
This PR fixes it.
=> make _DistributionSummary.from_file() a proper class method

src/pydistcheck/_compat.py, src/pydistcheck/cli.py
Contributes to #21.
Resolves the following warnings from `pylint`.
> src/pydistcheck/cli.py:16:0: C0411: standard import "from typing import Any, Dict, List, Optional, Union" should be placed before "import click" (wrong-import-order)
src/pydistcheck/cli.py:16:0: W0611: Unused Any imported from typing (unused-import)
src/pydistcheck/_compat.py:2:4: W0611: Unused import tomllib (unused-import)
src/pydistcheck/_compat.py:4:4: W0611: Unused tomli imported as tomllib (unused-import)
```shell
pylint ./src
```
=> resolve pylint warnings: unused imports

pyproject.toml
Contributes to #21.
Suppresses the following warnings from `pylint`.
> src/pydistcheck/checks.py:6:0: R0903: Too few public methods (1/2) (too-few-public-methods)
src/pydistcheck/checks.py:23:0: R0903: Too few public methods (1/2) (too-few-public-methods)
src/pydistcheck/checks.py:40:0: R0903: Too few public methods (1/2) (too-few-public-methods)
src/pydistcheck/cli.py:24:45: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
src/pydistcheck/cli.py:83:45: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
src/pydistcheck/distribution_summary.py:52:56: C0103: Variable name "tf" doesn't conform to snake_case naming style (invalid-name)
src/pydistcheck/distribution_summary.py:56:56: C0103: Variable name "f" doesn't conform to …
=> resolve pylint warnings: ignore unnecessary checks

src/pydistcheck/checks.py
Contributes to #21.
Resolves the following warnings from `pylint`.
> src/pydistcheck/checks.py:18:0: C0301: Line too long (116/100) (line-too-long)
src/pydistcheck/checks.py:35:0: C0301: Line too long (118/100) (line-too-long)
src/pydistcheck/checks.py:51:0: C0301: Line too long (104/100) (line-too-long)
=> resolve pylint warnings: long lines

.github/workflows/static-analysis.yml, Makefile, src/pydistcheck/cli.py, src/pydistcheck/distribution_summary.py, src/pydistcheck/utils.py
Fixes #21.
Resolves the remaining `pylint` warnings, and starts enforcing that `pylint` pass with 0 findings in CI.
Warnings addressed by this PR:
```text
src/pydistcheck/cli.py:8:0: C0411: standard import "from typing import Dict, List, Optional, Union" should be placed before "import click" (wrong-import-order)
src/pydistcheck/utils.py:13:4: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
src/pydistcheck/distribution_summary.py:67:15: R1728: Consider using a generator instead 'sum(1 for f in self.file_infos if f.is_directory)' (consider-using-generator)
src/pydistcheck/distribution_summary.py:71:15: R1728: Consider using a generator instead 'sum(1 for f in self.file_infos if f.is_file)' (consider-using-generator) …
```
=> [ci] enforce pylint checks (fixes #21)

.github/workflows/static-analysis.yml, Makefile, setup.cfg, src/pydistcheck/_compat.py, tests/test_cli.py
Fixes #20.
Enforces `flake8` checks in CI, and resolves the following warnings.
```text
./tests/test_cli.py:5:1: F401 'typing.List' imported but unused
./tests/test_cli.py:14:54: E741 ambiguous variable name 'l'
./tests/test_cli.py:16:101: E501 line too long (106 > 100 characters)
./tests/test_cli.py:62:101: E501 line too long (143 > 100 characters)
./tests/test_cli.py:88:101: E501 line too long (147 > 100 characters)
./src/pydistcheck/_compat.py:12:5: F401 'tomli as tomllib' imported but unused
```
=> [ci] enforce flake8 tests (fixes #20)

.github/workflows/static-analysis.yml, Makefile, bin/summarize-sizes.py, pyproject.toml, src/pydistcheck/checks.py, src/pydistcheck/cli.py, src/pydistcheck/utils.py, tests/test_cli.py, tests/test_distribution_summary.py, tests/test_utils.py
Fixes #28 .
Enforces `isort` sorting on the project's Python imports.
Uses the `black` profile to prevent `isort` and `black` from overwriting each others' changes: https://pycqa.github.io/isort/docs/configuration/black_compatibility.html.
=> [ci] add isort checks (fixes #28)

.github/workflows/static-analysis.yml, Makefile, pyproject.toml, src/pydistcheck/__init__.py, src/pydistcheck/_compat.py, src/pydistcheck/checks.py, src/pydistcheck/cli.py, src/pydistcheck/distribution_summary.py
Fixes #26.
Enforces checks from `mypy`, and addresses all of the warnings raised.
```text
src/pydistcheck/__init__.py:4: error: Need type annotation for "__all__" (hint: "__all__: List[<type>] = ...")
docs/conf.py:16: error: Need type annotation for "extensions" (hint: "extensions: List[<type>] = ...")
bin/summarize-sizes.py:3: error: Skipping analyzing "pandas": module is installed, but missing library stubs or py.typed marker
bin/summarize-sizes.py:3: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
src/pydistcheck/distribution_summary.py:79: error: Need type annotation for "out"
src/pydistcheck/_compat.py:9: error: Cannot find implementation or library stub for module named "tomllib"
src/pydistcheck/_compat.py:11: error: Name "tomllib" already defined …
```
=> [ci] add mypy checks (fixes #26)

.github/workflows/unit-tests.yml, README.md, src/pydistcheck/cli.py
Contributes to #46.
Starts some cleanup of the documentation, and moving more ideas for future development out of code comments and into the issue tracker.
=> [docs] misc. docs cleanup

Makefile, bin/run-smoke-tests.sh
Contributes to #79.
Moves the logic for the smoke tests into a shell script, so that it can be linted with `shellcheck` and evolved independent of the project's `Makefile`.
=> move smoke-tests logic into a script

Makefile, src/pydistcheck/checks.py
To convince `mypy` that all check classes in `checks.py` are callable, a `typing.Protocol` was added in #70.
That is kind of like an abstract base class...it defines methods and their signatures, but the actual implementations from there are never run.
This PR tells `pytest-cov` to ignore such lines.
=> [ci] exclude typing-only Protocol from code coverage

src/pydistcheck/distribution_summary.py, tests/test_distribution_summary.py
Contributes to #79.
Ensures that `pydistcheck --inspect` prints summarized file sizes in descending order by size, so the files that represent the largest portion of the distribution are at the top.
For example,
```shell
pydistcheck \
--inspect \
./tmp-dir/numpy/source/numpy-1.23.4.tar.gz
```
```text
file size
* compressed size: 10.2317M
* uncompressed size: 36.7684M
* compression space saving: 0.722
contents
* directories: 218
* files: 2222
* .py - 8950.6K (23.8%)
* .c - 7840.7K (20.8%)
* .rst - 3797.4K (10.1%)
* .js - 3693.1K (9.8%)
* .png - 3105.0K (8.2%)
* .s - 2140.5K (5.7%)
* .csv - 1323.2K (3.5%)
* .h - 1273.5K (3.4%)
* .svg - 1245.0K (3.3%)
* .src - 1031.4K (2.7%)
* .pyi - 840.1K (2.2%)
* .json - 692.5K (1.8%)
* .pyx - 480.6K (1.3%)
* .cpp - 374.2K (1.0%)
* .txt …
```
=> print file sizes in descending order

Makefile
As of PR, `make install` now uses and editable install with `pipx install -e`.
This should make local development easier, as it means that the package doesn't need to be re-installed to test changes.
=> use editable installs in local development

src/pydistcheck/cli.py
Adds beginning and end log messages, so it's clear where `pydistcheck`'s output begins and ends.
Like this
```text
python-package/dist/lightgbm-3.3.2.99-py3-none-manylinux1_x86_64.whl
pyproject options
{}
1. [too-many-files] Found 16 files. Only 1 allowed.
errors found while checking: 1
==================== done running pydistcheck ===============
```
=> add beginning and end log messages

tests/test_cli.py
Contributes to #71.
Adds a test checking that an informative error is raised if `pydistcheck` is passed a file that doesn't exist.
This is important because today, the project depends on `click`'s machinery to raise that exception.
https://github.com/jameslamb/pydistcheck/blob/499858c671dd436d0ee36e84e5098e2c4bf60df1/src/pydistcheck/cli.py#L25
=> add test on nonexistent file

Makefile, bin/full-run.sh, pyproject.toml, src/pydistcheck/cli.py, tests/test_cli.py
Fixes #71.
As of this PR, something like the following is now possible:
```shell
pydistcheck dist/*
```
Where `dist/*` contains multiple wheels and/or source distributions.
=> support checking multiple files in one call (fixes #71)

README.md, docs/README.md, docs/index.rst, docs/installation.rst
Fixes #63 .
adds...
* ... docs on how to develop the documentation locally
* ... "why `pydistcheck`?" type of information to the README and docs home page
* ... an installation guide page in the docs (including `conda-forge` instructions)
* ... conda-forge version and download badges
=> [docs] add installation and usage docs (fixes #63)

.github/workflows/static-analysis.yml, docs/conf.py, src/pydistcheck/utils.py, tests/test_distribution_summary.py, tests/test_utils.py
I read this excellent article from @MartinThoma tonight: https://towardsdatascience.com/static-code-analysis-for-python-bdce10b8d287, and learned about some `flake8` plugins I'd never seen before.
This PR enables of few of them in this project's CI:
* `flake8-bugbear`: correctness and efficiency related bugs that the `flake8` maintainers thought were too opinionated to be in `flake8`
* `flake8-builtins`: alert on variable names overriding builtins like `max`
* `flake8-comprehensions`: alert on common inefficient patterns with comprehensions
* `flake8-eradicate`: make sure CI fails on commented-out or unused code
Happy (?) to say this also caught a few bugs! `flake8-bugbear` caught some tests that were actually testing anything 🤩 
```text
./tests/test_distribution_summary.py:37:9: B007 …
```
=> [ci] add checks from flake8 plugins

docs/check-reference.rst
This adds one more doc to the explanation for why the `path-contains-non-ascii-characters` check.
Forgot to add the link from #76 in #102.
=> [docs] add another link about non-ASCII filenames

.github/workflows/check-docs.yml, .readthedocs.yaml, docs/conf.py, docs/configuration.rst, docs/env.yml, docs/index.rst
Contributes to #24 .
Adds a dedicated page in the docs describing how to configure `pyddistcheck`.
Uses [`sphinx-cilck`](https://sphinx-click.readthedocs.io/en/latest/) to automatically generate the main contents of that from the main CLI code in the project.
Also removes the unnecessary "Indices and tables" section in the docs homepage.
=> [docs] add configuration docs

.readthedocs.yaml
#105 had an incorrect readthedocs configuration, resulting in the following build error on that service.
> Problem in your project's configuration. Invalid "build.post_create_environment": .readthedocs.yaml: Invalid configuration option: build.post_create_environment. Make sure the key name is correct.
This fixes it.
=> [docs] fix readthedocs builds

src/pydistcheck/cli.py
Since #91, it's been possible to run `pydistcheck` over multiple files, like.
```shell
pydistcheck dist/*
```
This PR proposes adding a few blank lines to the output, to visually separate results from different packages.
```shell
pip install .
pydistcheck dist/*
```
```text
checking 'tests/data/base-package.tar.gz'
errors found while checking: 0
checking 'tests/data/base-package.zip'
errors found while checking: 0
checking 'tests/data/problematic-package.tar.gz'
1. [files-only-differ-by-case] Found files which differ only by case. Such files are not portable, since some filesystems are case-insensitive. Files: tmp/problematic-package/question.PY,tmp/problematic-package/question.py,tmp/problematic-package/Question.py
2. …
```
=> separate output for different distributions with blank lines

src/pydistcheck/cli.py
Adds default values to the output of `pydistcheck --help`.
```text
Options:
--inspect                       print diagnostic information about the
distribution
--max-allowed-files INTEGER     maximum number of files allowed in the
distribution  [default: 2000]
--max-allowed-size-compressed TEXT
maximum allowed compressed size, a string
like '1.5M' indicating '1.5 megabytes'.
Supported units: - B = bytes - K = kilobytes
- M = megabytes - G = gigabytes  [default:
50M]
--max-allowed-size-uncompressed TEXT
maximum allowed uncompressed size, a string
like '1.5M' indicating '1.5 megabytes'.
Supported units: - B = bytes - K = kilobytes
- M = megabytes - G = gigabytes  [default:
75M]
--help                          Show this message and exit
```
=> add defaults to '--help' docs

src/pydistcheck/checks.py, src/pydistcheck/cli.py, src/pydistcheck/config.py, tests/test_checks.py, tests/test_cli.py, tests/test_config.py
Fixes #80.
Adds the ability to selectively skip checks.
Like this
```shell
pydistcheck \
--ignore files-only-differ-by-case,path-contains-spaces \
tests/data/*
```
or this
```toml
[tool.pydistcheck]
ignore =
files-only-differ-by-case,
path-contains-spaces
```
=> add ability to ignore some checks (fixes #80)

src/pydistcheck/cli.py, src/pydistcheck/inspect.py
Adds some `----` lines in output to separate the results from inspection (`pydistcheck --inspect`) and checks.
```shell
pip install .
pydistcheck \
--ignore=path-contains-spaces \
--inspect \
tests/data/*
```
Now prints the following:
```text
checking 'tests/data/base-package.tar.gz'
file size
* compressed size: 4.124K
* uncompressed size: 11.123K
* compression space saving: 0.629
contents
* directories: 1
* files: 3
* .txt - 11.1K (99.7%)
* .py - 0.0K (0.3%)
errors found while checking: 0
checking 'tests/data/base-package.zip'
file size
* compressed size: 4.6006K
* uncompressed size: 11.123K
* …
```
=> visually separate inspection and checking results in output

src/pydistcheck/inspect.py
Contributes to #79.
Makes it more obvious that compression space savings as reported by `pydistcheck --inspect` is a percentage.
Before:
```text
file size
* compressed size: 6.3779K
* uncompressed size: 11.5596K
* compression space saving: 0.448
```
After:
```text
file size
* compressed size: 6.3779K
* uncompressed size: 11.5596K
* compression space saving: 44.8%
````
=> clarify compression space savings in pydistcheck --inspect

src/pydistcheck/utils.py, tests/test_cli.py, tests/test_utils.py
Contributes to #79.
There are a few places where `pydistcheck` needs to turn a file size in number of byes into a human-readable string:
* check warnings for checks like `distro-too-large-compressed`
* total file size and cumulative size by file type in `pydistcheck --inspect`
This PR proposes changes to that "what string should be used to represent this size" logic that I hope will make the tool's logs a bit easier to understand.
```shell
pydistcheck \
--inspect \
--max-alllowed-size-compressed=1B \
tests/data/problematic-package.tar.gz
```
Before:
```text
file size
* compressed size: 4.5117K
* uncompressed size: 11.5596K
* compression space saving: 0.61
* .txt - 11.1K (96.0%)
* .py - 0.4K (3.2%)
* .PY - 0.1K (0.6%)
* .ini - 0.0K (0.2%)
------------ check results …
```
=> simplify file size strings in logs

tests/test_cli.py
Many of the project's unit tests re-use the same set of test distributions, referenced in repeated string literals.
This PR consolidates those into module-level constants, so...
* it's easier to add new test distributions in the future
* there's less risk of new tests not covering all of the distribution types
=> [ci] consolidate references to test data

.github/workflows/smoke-tests.yml, Makefile
Contributes to #78 .
Runs the smoke tests on Windows, to hopefully catch Windows-specific characteristics of distributions that `pydistcheck` wouldn't otherwise correctly handle.
This is extra important at this moment, when the project's unit tests don't test against wheels (to be added in #124).
=> [ci] run smoke tests on Windows

.github/workflows/smoke-tests.yml, .github/workflows/unit-tests.yml
Reverts #132 , #133, #134, #135.
Switches to https://github.com/re-actors/alls-green for enforcing branch protections.
=> [ci] switch to alls-good for branch protections

bin/run-smoke-tests.sh
Today, the smoke tests in this project are structured like this:
* download distribution files for many projects into the same directory
* run `pydistcheck ${directory}/*` to check all of them at once
Some of the checked packages raise some warnings with `pydistcheck`'s default values.
To ensure that the smoke tests fail only for runtime errors in `pydistcheck`, some of those defaults are modified.
https://github.com/jameslamb/pydistcheck/blob/aa70dbd3ba2a5c55f39f97afac2e0256e82599cc/bin/run-smoke-tests.sh#L39-L44
This PR proposes switching the approach to running `pydistcheck` once per project in those tests.
This increases the coverage of the tests by:
* avoiding the need to skip checks with `--ignore`
* making it clearer how likely `pydistcheck`'s default values are to result in …
=> [ci] increase smoke test coverage

docs/_static/defaults.toml, docs/configuration.rst, tests/test_docs.py
Contributes to #55.
Modifies the example `pyproject.toml` content in the docs to contain all configurable options and their default values.
Also adds a unit test confirming that that file matches `pydistcheck`'s actual configuration.
* makes it easier for users to modify `pydistcheck`'s configuration (just copy this file and change what you want)
* adds a bit of extra test coverage of stuff in `pydistcheck.config`
* ensures that the docs evolve as the library does
* allows for clearly documenting longer default values, like the lists of patterns in #55
=> [docs] add defaults for all options to "Configuration" doc

tests/test_docs.py
Contributes to #55.
All checks that `pydistcheck` runs are documented at https://pydistcheck.readthedocs.io/en/latest/check-reference.html.
When `pydistcheck` raises an error like
> [some-check] Found a problem etc. etc.
it's expected that users will be able to go to that page and fine a corresponding `some-check` section providing more details on why `pydistcheck` is warning about that and how to resolve it.
This PR proposes adding a unit test to prevent new checks from being added without that doc also being updated.
I hope this will reduce the risk of the documentation and code drifting too far apart.
=> [ci] test that all checks are documented in Check Reference

bin/create-test-data-bdist.sh
Contributes to #54.
Simplifies `create-data-bdist` script by removing a bit of duplication and unnecessary specificity in the wheel tags.
=> [ci] simplify create-data-bdist script

src/pydistcheck/checks.py, src/pydistcheck/config.py
`black` 23.x was released recently.
This PR makes `pydistcheck` compliant with it.
=> use black 23.x

.github/workflows/unit-tests.yml, Makefile, pyproject.toml, requirements-tests.txt, requirements.txt
Contributes to #146.
* adds checks in CI that distributions (sdists and wheels) are well-formed
- `gunzip -t` = "are the sdists valid tar.gz files?"
- `unzip -T` = "are the wheels valid zip files?"
- `twin check` = "is the package README (which'll become the PyPI homepage) well-formed?"
- `pyroma` = "do the sdists have useful, descriptive metadata? are they free from some common misconfiguration issues?"
- `check-wheel-contents` = "are the wheels free from some common sources of unnecessary files? do their internal files structures follow standard Python library patterns?"
* removes unnecessary `requirements.txt` file
=> [ci] check dists

src/pydistcheck/checks.py, tests/test_cli.py
Text like "this is not portable" in error messages isn't necessary, given that `pydistcheck` prints error messages with error IDs that map to details descriptions at https://pydistcheck.readthedocs.io/en/latest/check-reference.html.
=> simplify error messages

.github/workflows/smoke-tests.yml, bin/run-smoke-tests.sh
Adds more projects to the smoke tests, and adds a trigger to run the smoke tests once a week (regardless of activity in this repo).
Taken together, these changes are intended to:
* help expose issues in `pydistcheck`
* detect more portability issues in popular scientific Python projects (and therefore identify opportunities for contributions)
=> [ci] check more projects in smoke tests

README.md
updates the quickstart docs to:
* show off the new checks
* show an example of the output when debug symbols are found in compiled objects
=> [docs] update quickstart

MANIFEST.in
Minor simplifications to `MANIFEST.in`.
* explicitly `include`-ing `README.md` isn't necessary because `MANIFEST.in` processing automatically does that ([docs](https://packaging.python.org/en/latest/guides/using-manifest-in/))
* explicitly `include`-ing `LICENSE` isn't necessary since it's mentioned in `pyproject.toml`
https://github.com/jameslamb/pydistcheck/blob/c10a5f58d5a9bf58620a30421ebc64b1e970285e/pyproject.toml#L28
* `graft` is a bit more appropriate than `recursive-include` for "include everything in this directory"
=> remove unnecessary MANIFEST.in lines

bin/run-smoke-tests.sh
`catboost` 1.2 was released yesterday, and contained some packaging changes that triggered more checks in this project's smoke tests.
```text
checking './smoke-tests/catboost-1.2-cp310-cp310-macosx_11_0_universal2.whl'
errors found while checking: 0
checking './smoke-tests/catboost-1.2-cp310-cp310-manylinux2014_aarch64.whl'
1. [distro-too-large-uncompressed] Uncompressed size 0.3G is larger than the allowed size (0.2G).
errors found while checking: 1
checking './smoke-tests/catboost-1.2-cp310-cp310-win_amd64.whl'
1. [distro-too-large-uncompressed] Uncompressed size 0.3G is larger than the allowed size (0.2G).
errors found while checking: 1
checking …
```
=> [ci] fix catboost checks in smoke tests

README.md, docs/configuration.rst, src/pydistcheck/cli.py, tests/test_cli.py
Fixes #171.
By default, `pydistcheck` looks for configuration in a `pyproject.toml` in the working directory it's called from.
This adds the ability to override that behavior and point to a specific TOML file via a command-line argument.
I chose to name that argument `--config`, for consistency with `check-wheel-contents`, `flake8`, `pydocstyle`, and `ruff`.
=> support specifying an exact config location (fixes #171)

bin/run-smoke-tests.sh
Updates smoke tests to work with the latest versions of all the projects it checks.
To fix the following new errors, observed in #177
```text
checking './smoke-tests/opencv-python-4.8.0.74.tar.gz'
1. [too-many-files] Found 7206 files. Only 7200 allowed.
errors found while checking: 1
```
([link to failing build](https://github.com/jameslamb/pydistcheck/actions/runs/5440690446/jobs/9893868473?pr=177))
=> [ci] add more exceptions in smoke tests

pyproject.toml, setup.cfg
Continuation of #156.
* moves dependencies out of `setup.cfg` and into `pyproject.toml`
* removes `python_requires` in `setup.cfg`, which is redundant with the one in `pyproject.toml`
https://github.com/jameslamb/pydistcheck/blob/f6b8027f44472461b1037fc0db98a988ac66144b/pyproject.toml#L34
Specifying dependencies via the `[options]` table in `setup.cfg` is deprecated in the `setuptools.build_meta` build backend (see e.g. https://github.com/pypa/setuptools/issues/3300).
As a result of PEP 621/ PEP 631, see https://peps.python.org/pep-0631/.
I actually stumbled over something similar recently in LightGBM: https://github.com/microsoft/LightGBM/pull/5942.
=> [PEP 631] move dependencies into pyproject.toml

Makefile, setup.cfg, src/pydistcheck/checks.py, src/pydistcheck/cli.py, src/pydistcheck/config.py, src/pydistcheck/inspect.py, src/pydistcheck/shared_lib_utils.py
This project's `setup.cfg` contains some configuration to achieve the same effect as invoking `setuptools.find_packages()` in a `setup.py`.
https://github.com/jameslamb/pydistcheck/blob/f6b8027f44472461b1037fc0db98a988ac66144b/setup.cfg#L4-L5
https://github.com/jameslamb/pydistcheck/blob/f6b8027f44472461b1037fc0db98a988ac66144b/setup.cfg#L10-L15
While working on #177, I was starting to look into whether that could be moved into `pyproject.toml`. In the `setuptools` docs about that ([link](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html)), I saw the following description of the `setuptools` table(s) in `pyproject.toml`.
> *some `setuptools`-specific configurations ... are completely optional and probably can be skipped when creating simple packages...*
`pydistcheck` is …
=> simplify internal imports and related packaging config

docs/check-reference.rst
Adds a reference to https://github.com/jqlang/jq/issues/811 to the docs on the non-ASCII check.
=> [docs] add example of issue with non-ASCII file names

.github/workflows/static-analysis.yml, Makefile, bin/get-release-files.py, docs/conf.py, pyproject.toml, src/pydistcheck/__init__.py, src/pydistcheck/_compat.py, src/pydistcheck/checks.py, src/pydistcheck/cli.py, src/pydistcheck/config.py, src/pydistcheck/distribution_summary.py, tests/test_config.py, tests/test_utils.py
Replaces uses of `flake8` and some extensions for it with `ruff`.
`ruff` is faster, implements all the same checks, and has a bunch of other built-in sets of checks.
This PR also fixes the following new warnings from `ruff`:
```text
docs/conf.py:10:33: RUF100 [*] Unused `noqa` directive (non-enabled: `A001`)
src/pydistcheck/__init__.py:4:15: PGH003 Use specific rule codes when ignoring type issues
src/pydistcheck/_compat.py:9:21: PGH003 Use specific rule codes when ignoring type issues
src/pydistcheck/_compat.py:9:37: RUF100 [*] Unused `noqa` directive (unused: `F401`)
src/pydistcheck/_compat.py:11:30: PGH003 Use specific rule codes when ignoring type issues
src/pydistcheck/config.py:65:42: RUF009 Do not perform function call in dataclass defaults
src/pydistcheck/config.py:66:37: RUF009 …
```
=> [ci] use ruff for static analysis

Makefile, pyproject.toml, src/pydistcheck/_compat.py, src/pydistcheck/distribution_summary.py
Adds use of `--strict` to `mypy` in this project, to get even more thorough type-checking.
See https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-strict
Resolves the following errors raised by it:
```text
src/pydistcheck/distribution_summary.py:212: error: Missing type parameters for generic type "OrderedDict"  [type-arg]
src/pydistcheck/_compat.py:9: error: Unused "type: ignore[var-annotated]" comment  [unused-ignore]
src/pydistcheck/config.py:11: error: Module "pydistcheck._compat" does not explicitly export attribute "tomllib"  [attr-defined]
```
=> [ci] use 'mypy --strict'

src/pydistcheck/distribution_summary.py, src/pydistcheck/inspect.py, tests/test_distribution_summary.py
fixes #121
As of this PR, `pydistcheck --inspect` prints the 5 largest files in the distribution.
=> add 5 largest files to --inspect (fixes #121)

bin/run-smoke-tests.sh
As of `numpy==1.26.1`, `numpy` have decided to bundle 4200+ additional files from `meson`.
That results in 3800+ new errors when checking `numpy` w/ `pydistcheck`, summarized as follows:
```text
1. [mixed-file-extensions] Found a mix of file extensions for the same file type: .cc (35), .cpp (156)
2. [mixed-file-extensions] Found a mix of file extensions for the same file type: .yaml (94), .yml (60)
3-3883. [path-contains-spaces] Found path with spaces ...
...
3884. [too-many-files] Found 7261 files. Only 3000 allowed.
errors found while checking: 3884
```
([build link](https://github.com/jameslamb/pydistcheck/actions/runs/6727481097/job/18285335876?pr=190))
The inclusion of all these new files appears to be intentional:
* https://github.com/numpy/numpy/issues/23981#issuecomment-1656241060 …
=> [ci] fix numpy checks in smoke tests

pyproject.toml, src/pydistcheck/checks.py, tests/test_distribution_summary.py
Proposes enforcing the `perflint` checks in this project's CI.
Fixes the following:
```text
src/pydistcheck/checks.py:122:29: PERF102 When using only the values of a dict use the `values()` method
tests/test_distribution_summary.py:86:29: PERF102 When using only the values of a dict use the `values()` method
tests/test_distribution_summary.py:203:29: PERF102 When using only the values of a dict use the `values()` method
```
For more, see https://github.com/tonybaloney/perflint and https://docs.astral.sh/ruff/rules/#perflint-perf.
=> [ci] enforce perflint checks

.github/workflows/unit-tests.yml, Makefile, pyproject.toml
Adds CI jobs testing against CPython and Pypy 3.11 and 3.12.
Updates the trove classifiers in package metadata indicating that version support.
=> support CPython 3.11/3.12 and Pypy 3.10

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/new-check.yml, .github/release-drafter.yml, .github/workflows/build-and-publish-wheels.yml, .github/workflows/check-docs.yml, .github/workflows/manual-run.yml, .github/workflows/release-drafter.yml, .github/workflows/smoke-tests.yml, .github/workflows/static-analysis.yml, .github/workflows/unit-tests.yml, .readthedocs.yaml, Makefile, docs/env.yml
Fixes #195.
Addresses the following:
```text
./.readthedocs.yaml
1:1       warning  missing document start "---"  (document-start)
./docs/env.yml
1:1       warning  missing document start "---"  (document-start)
./.github/release-drafter.yml
1:1       warning  missing document start "---"  (document-start)
./.github/workflows/static-analysis.yml
1:1       warning  missing document start "---"  (document-start)
6:5       error    wrong indentation: expected 6 but found 4  (indentation)
9:5       error    wrong indentation: expected 6 but found 4  (indentation)
./.github/workflows/manual-run.yml
1:1       warning  missing document start "---"  (document-start)
./.github/workflows/smoke-tests.yml
1:1       warning  missing document start "---"  (document-start)
6:5       error    wrong …
```
=> [ci] enforce yamllint checks (fixes #195)

bin/run-smoke-tests.sh
Some `tensorflow==2.15.0` artifacts contain debug symbols, and there are 2000+ more files in some of those wheels than in the previous release.
([build link](https://github.com/jameslamb/pydistcheck/actions/runs/7468436323/job/20323870249))
This adds more exceptions to the smoke test configuration to account for that.
=> [ci] fix cmake and tensorflow checks in smoke tests

bin/run-smoke-tests.sh, src/pydistcheck/config.py, src/pydistcheck/shared_lib_utils.py, tests/test_cli.py
Running this project's unit tests on my mac today (macOS 12.2.1, intel chip), I found 2 test failures that don't show up in CI:
```text
E       AssertionError: ==================== running pydistcheck ====================
E         
E         checking '/Users/jlamb/repos/pydistcheck/tests/data/baseballmetrics-0.1.0-py3-none-macosx_10_15_x86_64.macosx_11_6_x86_64.macosx_12_5_x86_64.whl'
E         ------------ check results -----------
E         1. [compiled-objects-have-debug-symbols] Found compiled object containing debug symbols. For details, extract the distribution contents and run 'nm --debug-syms "lib/lib_baseballmetrics.dylib"'.
```
It seems that the `nm` distributed with Xcode does not support argument `--debug-syms` ([docs](https://keith.github.io/xcode-man-pages/nm.1.html)), …
=> fix compiled-objects-have-debug-symbols on macOS

.github/workflows/build-and-publish-wheels.yml
Starting with v4 of https://github.com/actions/upload-artifact, a single workflow run cannot upload multiple artifacts with the same name.
As a result, publishing v0.5.2 to PyPI failed like this:
```text
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
([build link](https://github.com/jameslamb/pydistcheck/actions/runs/7677156874))
=> [ci] fix package uploads

src/pydistcheck/__init__.py
Bumping the version to `0.5.2.99`, per https://github.com/jameslamb/pydistcheck/blob/main/CONTRIBUTING.md.
=> bump development version

.gitignore
Adds more extensions for packaging-related files to `.gitignore`.
=> [ci] add more extensions to gitignore

src/pydistcheck/distribution_summary.py, src/pydistcheck/file_utils.py
Contributes to #200 .
Starts to move some internal functions and dataclasses related to files out of `srs/distribution_summary.py` and into a module `src/file_utils.py`.
Having checks in `checks.py` import `distribution_summary` creates a circular dependency problem (since other modules want to import both of them). Moving this stuff into a place they both import helps with that.
See #204 for more details on where these changes are going.
=> introduce file_utils module

src/pydistcheck/distribution_summary.py, src/pydistcheck/file_utils.py
Currently, this project only supports 3 formats:
* `.whl` (zip-format built distribution)
* `.tar.gz` (gzip-compressed, tar-format source distribution)
* `.zip` (zip-format distribution)
Adding conda package support will add 2 more things:
* `.tar.bz2` (gzip-compressed, tar-format distribution)
* `.conda` (bzip2-compress, zip-format distribution containing multiple zstd-compressed tar-format archives)
This PR centralizes the code for determining which, if any, of those formats a provided file is in. That should help reduce duplication, and provide a clearer place to work on in the future to make that detection more reliable than simple pattern-matching on file extensions.
=> centralize archive-format detection

bin/get-release-files.py
Adds `linux_i386`, `linux_x86_64`, and `win32` wheels (like those `MarkupSafe` provides at https://pypi.org/project/MarkupSafe/#files) to smoke tests.
See https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/#basic-platform-tags.
Also removes a bit of unused code in smoke tests.
=> [ci] add win32 and linux_* wheels to smoke tests

src/pydistcheck/distribution_summary.py, src/pydistcheck/file_utils.py, src/pydistcheck/shared_lib_utils.py
Moves more file-processing code out of `src/distribution_summary`, so that module can be narrowly focused on the `_DistributionSummary` (the main data structure checks run against), and so those file-processing things can be used by other parts of the codebase.
See #204 for where this is going.
=> move compiled-object detection code out of distribution_summary

pyproject.toml
Adds a trove classifier indicating that `pydistcheck` works on Windows.
Specific formatting from https://github.com/pypa/trove-classifiers/blob/e5c379567a6a5d67c5a2505d6429faca5b69fc45/src/trove_classifiers/__init__.py#L404.
This helps categorization on indices like PyPI, e.g. to support queries like "all projects that say they work on Windows".
This project's full test suite runs on Windows on every commit.
=> [docs] add Windows trove classifier

bin/get-release-files.py, pyproject.toml, src/pydistcheck/file_utils.py
Adds the `flake8-bandit` checks (run by `ruff`) to the project's linting.
From https://pypi.org/project/flake8-bandit/
> *Automated security testing built right into your workflow*
It found these things:
```text
bin/get-release-files.py:13:7: S113 Probable use of requests call without timeout
bin/get-release-files.py:64:11: S113 Probable use of requests call without timeout
src/pydistcheck/file_utils.py:124:9: S101 Use of `assert` detected
src/pydistcheck/shared_lib_utils.py:21:33: S603 `subprocess` call: check for execution of untrusted input
```
=> [ci] add flake8-bandit checks

pyproject.toml, src/pydistcheck/checks.py, src/pydistcheck/file_utils.py, src/pydistcheck/shared_lib_utils.py
The `compiled-objects-have-debug-symbols' checks works by extracting actual file content from a file distribution, writing it out to a temporary directory, and then running a bunch of tools against it using `subprocess`.
Today, it does that with logic like this pseudcode:
```text
for file in list_of_compiled_objects:
tmp_dir = create_temp_directory()
extract_to_tmp_dir(archive, file, tmp_dir)
for tool in symbol_checking_tools:
run_tool(tool, f"{tmp_dir}/{file}")
```
For packages with `n` compiled objects, that pattern will result in creating and deleting `n` temporary directory, and extracting files by opening the archive file `n` times.
This PR proposes extracting all of the relevant files at once... 1 temporary directory, 1 time opening the archive file. Like this …
=> avoid duplicate file I/O for 'compiled-objects-have-debug-symbols'

pyproject.toml, src/pydistcheck/cli.py, tests/test_cli.py
`pydistcheck` currently returns a different exit code depending on how many errors are found.
https://github.com/jameslamb/pydistcheck/blob/bfcaa481ba1f9f1398b4fa04d85bc129949a8d1f/src/pydistcheck/cli.py#L229
That's unnecessary... it's enough for all use cases I can think of for `pydistcheck` to exit with 0 on success and 1 on not success.
But worse than that... this scheme opens up the possibility of returning exit codes `>255`. Some operating systems don't support those, and even worse... some will wrap around, like this:
```shell
cat << EOF > ./test.sh
exit 256
EOF
sh ./test.sh
echo $?
```
😱 in that case, running `pydistcheck` on a file with exactly 256  issues (or 512, or 768, etc.) would look like a success to the operating system. That's problematic for any non-interactive cases, …
=> prevent exit codes greater than 255

src/pydistcheck/cli.py, src/pydistcheck/file_utils.py, src/pydistcheck/inspect.py, tests/test_cli.py
As of v0.5.2, when you run `pydistcheck` on a file that isn't in one of the formats it recognizes, the response is a little unpleasant.
```shell
pydistcheck ./README.md
```
```text
checking './README.md'
Traceback (most recent call last):
File "/Users/jlamb/mambaforge/envs/pydistcheck-dev/bin/pydistcheck", line 8, in <module>
sys.exit(check())
^^^^^^^
File "/Users/jlamb/mambaforge/envs/pydistcheck-dev/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/jlamb/mambaforge/envs/pydistcheck-dev/lib/python3.11/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx) …
```
=> raise an informative error on unrecognized file format

src/pydistcheck/cli.py, src/pydistcheck/file_utils.py
Adds more enforcement of keyword-only arguments in some internal functions, to make the flow of configuration stricter.
=> enforce more uses of keyword-only arguments

pyproject.toml, src/pydistcheck/utils.py
Fixes these things found by `flake8-pyi` (via `ruff`):
```text
src/pydistcheck/utils.py:40:29: PYI032 [*] Prefer `object` to `Any` for the second parameter to `__eq__`
src/pydistcheck/utils.py:55:29: PYI032 [*] Prefer `object` to `Any` for the second parameter to `__ne__`
```
From the `ruff` docs:
> The Python documentation recommends the use of `object` to "indicate that a value could be any type in a typesafe manner", while `Any` should be used to "indicate that a value is dynamically typed."
> The semantics of `__eq__` and `__ne__` are such that the obj parameter should be any type, as opposed to a dynamically typed value. Therefore, the object type annotation is more appropriate.
([link](https://docs.astral.sh/ruff/rules/any-eq-ne-annotation/))
=> [ci] enforce flake8-pyi checks

src/pydistcheck/distribution_summary.py, src/pydistcheck/inspect.py
Consider the following:
```shell
pydistcheck --inspect ./downloads/linux-64-pytorch-2.2.0-py3.10_cpu_0.tar.bz2
```
```text
file size
* compressed size: 79.4M
* uncompressed size: 0.4G
* compression space saving: 79.3%
contents
* directories: 0
* files: 12076 (11 compiled)
* .so - 298893.6K (76.1%)
* .py - 25532.7K (6.5%)
* .h - 25511.6K (6.5%)
* .pyc - 19139.5K (4.9%)
* .txt - 6748.1K (1.7%)
* no-extension - 6236.5K (1.6%)
* .0 - 5213.9K (1.3%)
* .json - 3005.1K (0.8%)
* .yaml - 742.5K (0.2%)
* .pyi - 626.9K (0.2%)
* .cuh - 600.7K (0.2%)
...
largest files
* (0.3G) lib/python3.10/site-packages/torch/lib/libtorch_cpu.so
* (22.1M) lib/python3.10/site-packages/torch/lib/libtorch_python.so
* (6.6M) …
```
=> make --inspect file sizes consistent with other output

.github/workflows/build-and-publish-wheels.yml
Fixes this: https://github.com/jameslamb/pydistcheck/actions/runs/7946995638/job/21695328634
```text
Run actions/download-artifact@v4
Downloading single artifact
Error: Unable to download artifact(s): Artifact not found for name: artifact
Please ensure that your artifact is not expired and the artifact was uploaded using a compatible version of toolkit/upload-artifact.
For more information, visit the GitHub Artifacts FAQ: https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md
```
=> [ci] another upload-artifact fix

.github/workflows/static-analysis.yml, .github/workflows/unit-tests.yml, .pre-commit-config.yaml, Makefile, bin/get-conda-release-files.py, bin/get-pypi-files.py, pyproject.toml, src/pydistcheck/checks.py, src/pydistcheck/cli.py, src/pydistcheck/config.py, src/pydistcheck/distribution_summary.py, src/pydistcheck/file_utils.py, src/pydistcheck/inspect.py, src/pydistcheck/shared_lib_utils.py, src/pydistcheck/utils.py, tests/data/baseballmetrics/CMakeLists.txt, tests/data/baseballmetrics/baseballmetrics/_shared_lib.py, tests/data/baseballmetrics/baseballmetrics/metrics.py, tests/test_cli.py, tests/test_config.py, tests/test_distribution_summary.py
Also switches from `black` to `ruff-format` for autoformatting Python code.
=> [ci] use pre-commit to run some autoformatting and linting

docs/how-to-test-a-python-distribution.rst
Fixes #234
Fixes #232
Fixes #199
Adds `conda-verify`, `pkginfo`, and `repairwheel` to the "How to Test a Python Distribution" doc.
Also updates the description of `pydistcheck` in that doc to clarify that it supports conda packages.
=> [docs] add more tools to 'How to Test a Python Distribution'

.github/dependabot.yml, .github/workflows/smoke-tests.yml, .pre-commit-config.yaml, .readthedocs.yaml, docs/README.md, docs/installation.rst
* adds configuration to get dependabot to automatically recommend updating third-party GitHub Actions
* changes readthedocs configuration to "latest" types of versions that'll keep automatically updating as readthedocs does
* updates pre-commit versions (ran `pre-commit autoupdate`)
* switches commands from `mamba {cmd}` back to `conda {cmd}`
- *`conda` now includes `libmamba` as its default solver, no more need to use the `mamba` command*
* https://docs.readthedocs.io/en/latest/config-file/v2.html#build-tools-python
* https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
* https://conda.org/blog/2023-11-06-conda-23-10-0-release/
=> [ci] update some CI dependencies, add dependabot

bin/check-test-packages.sh, bin/run-smoke-tests.sh, docs/_static/defaults.toml, docs/check-reference.rst, src/pydistcheck/checks.py, src/pydistcheck/cli.py, src/pydistcheck/config.py, tests/test_cli.py, tests/test_config.py
Fixes #233.
Adds a new check, `[expected-files]`, which allows the use of `pydistcheck` to assert that a distribution contains certain files or directories.
For example:
```toml
[tool.pydistcheck]
expected_files = [
"*.py",
"!.a",
"coolpkg/resources/templates/the-template.j2"
]
```
Calling this `breaking` because it changes some parameters:
* `--unexpected-directory-patterns` to `--expected-directories`
* `--unexpected-file-patterns` to `--expected-files`
=> add expected-files check, rename '--unexpected-file-patterns' to '--expected-files' (fixes #233)

docs/_static/defaults.toml, docs/check-reference.rst, src/pydistcheck/checks.py, src/pydistcheck/cli.py, src/pydistcheck/config.py, tests/test_cli.py, tests/test_config.py
Fixes #74
Fixes #189
Adds a check, `path-too-long`, to prevent the inclusion of long filepaths in archives.
=> add path-too-long check

README.md, docs/check-reference.rst, docs/how-to-test-a-python-distribution.rst, docs/index.rst
Expands docs on how to test a Python distribution.
Adds link to https://github.com/pre-commit/pre-commit-hooks/issues/760 (which leads to https://github.com/pre-commit/pre-commit-hooks/issues/1007 and https://github.com/ShellMagick/commit-hooks/issues/1) to the `path-too-long` check.
=> [docs] expand docs on testing a Python distribution

.pre-commit-config.yaml, docs/check-reference.rst, docs/env.yml
Fixes some formatting issues introduced in the docs added in #244
Before:
After:
Reference: https://restructuredtext.readthedocs.io/en/latest/rst_guide.html#blockquotes
While I'm in here, also:
* updates versions of dependencies for docs builds
* updates versions in `pre-commit` via `pre-commit autoupdate`
Enabled builds on readthedocs.
build: https://readthedocs.org/projects/pydistcheck/builds/24477913/
docs: https://pydistcheck.readthedocs.io/en/docs-fix/check-reference.html#path-too-long
=> [docs] fix formatting of blockquotes

.github/workflows/static-analysis.yml, .pre-commit-config.yaml, Makefile, bin/create-release-pr
Moves `shellcheck` into `pre-commit` checks, and uses https://github.com/shellcheck-py/shellcheck-py so it can be installed automatically from PyPI (instead of needing to be installed separately before running linting).
This also uses `pre-commit`'s mechanism for detecting files, and doesn't rely on file extensions. So it caught a few other uncaught `shellcheck` things in other files 🙌🏻
=> [ci] move shellcheck to pre-commit, use shellcheck-py

.github/workflows/static-analysis.yml, .pre-commit-config.yaml, Makefile
Proposes using `shfmt-py` to run `shfmt` via `pre-commit`.
ref: https://github.com/MaxWinterstein/shfmt-py
That simplifies the configuration a bit and removes the need to do an `apt-get install` in the linting CI job.
=> [ci] use shfmt-py in pre-commit to run shfmt

README.md, src/pydistcheck/__init__.py
Also bumps development version to `0.7.1.99`.
=> [docs] add example with 'pip download'

.github/workflows/check-docs.yml, .github/workflows/smoke-tests.yml, .github/workflows/unit-tests.yml, .pre-commit-config.yaml, bin/run-smoke-tests.sh
The `conda-incubator/setup-miniconda` action is raising these warnings sometimes treated as errors:
> *Warning: Future Miniforge releases will NOT build Mambaforge installers. We advise you switch to Miniforge at your earliest convenience. More details at https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/.*
> *Warning: ERROR: executing pre_install.sh failed*
This fixes that by just switching to miniforge, per https://github.com/conda-incubator/setup-miniconda?tab=readme-ov-file#example-10-miniforge.
It also updates pre-commit hook versions with `pre-commit autoupdate`.
=> [ci] stop using mambaforge

tests/test_config.py
Contributes to #264.
The tests on `_Config.update_from_dict()` don't test that the `ignore` parameter is updated correctly. This fixes that.
=> [ci] test that _Config.update_from_dict() updates 'ignore' param

.github/workflows/smoke-tests.yml, .github/workflows/unit-tests.yml, .pre-commit-config.yaml, docs/env.yml, pyproject.toml, src/pydistcheck/cli.py, tests/test_cli.py, tests/test_utils.py
* adds Python 3.13 support
* adds all runtime dependencies to `pre-commit` env for `mypy`, so it can run more thorough checks
* updates all `pre-commit` hooks with `pre-commit autoupdate`
Fixes the following new `ruff` errors:
```text
tests/test_config.py:11:17: PT003 `scope='function'` is implied in `@pytest.fixture()`
tests/test_cli.py:114:35: PT007 Wrong values type in `@pytest.mark.parametrize` expected `list` of `tuple`
tests/test_cli.py:799:12: PIE810 Call `startswith` once with a `tuple`
tests/test_utils.py:47:5: PT006 Wrong type passed to first argument of `@pytest.mark.parametrize`; expected `tuple`
```
=> add Python 3.13 support, misc. CI improvements

.pre-commit-config.yaml, docs/check-reference.rst, docs/configuration.rst, pyproject.toml
Adds linting on the docs with `rstcheck` (https://github.com/rstcheck/rstcheck).
This caught a few small issues 🎉 
```text
docs/check-reference.rst:120: (ERROR/3) (python) expected an indented block after 'if' statement on line 1
docs/configuration.rst:23: (INFO/1) No directive entry for "click" in module "docutils.parsers.rst.languages.en".
docs/configuration.rst:23: (ERROR/3) Unknown directive type "click".
docs/configuration.rst:18: (INFO/1) Hyperlink target "cli-arguments" is not referenced.
docs/configuration.rst:27: (INFO/1) Hyperlink target "pyproject-toml" is not referenced.
Error! Issues detected.
```
=> [ci] check docs with 'rstcheck'

docs/_static/defaults.toml, pyproject.toml, src/pydistcheck/cli.py, src/pydistcheck/config.py, tests/test_cli.py, tests/test_config.py, tests/test_docs.py
fixes #264
Introduces a new configuration option, `--select`, with usage similar to `ruff`'s option of the same name. If this flag (or the corresponding `pyproject.toml` option) is supplied, it switches `pydistcheck` from opt-out behavior ("run all checks except those in `ignore`") to opt-in behavior ("run only the checks indicated by `select`").
For example, to say "only run the checks on file size" and avoid running any others:
```shell
pydistcheck \
--select 'distro-too-large-compressed' \
--max-distro-size-compressed '100M' \
--select 'distro-too-large-uncompressed' \
--max-distro-size-uncompressed '300M' \
dist/*.whl
```
=> add --select option to make checks opt-in

Makefile, pyproject.toml
`if TYPE_CHECKING` blocks contain code/imports that are only executed when using a type checker like `pyright` or `mypy`... not code that executes during normal usage of this tool.
This proposes excluding blocks like that from code coverage calculations, to focus development on covering the codepaths that are accessed during normal usage.
=> [ci] skip TYPE_CHECKING blocks in code coverage

src/pydistcheck/cli.py, src/pydistcheck/utils.py, tests/test_utils.py
fixes #274
Some configuration options, like `--max-allowed-size-compressed`, allow you to change file-size-based thresholds that influence check results.
These are currently evaluated in "bibytes", but are not correctly document. e.g. `"1M" = "1 mebibyte" = 1024^2 bytes`, but `pydistcheck` docs say that `"1M" = "1 megabyte"`, which is 1,000,000 bytes.
This PR:
* fixes those docs
* adds support for using the clearer form like `Mi` or `Gi`
* adds support for really specifying sizes in other units, like `"MB"` for megabytes
* ignores case, so that now these would all evaluate to the same number of bytes: `5KB, 5kB, 5Kb, 5kb`
To avoid breaking any existing `pydistcheck` uses that have been relying on that behavior.
And because I couldn't find any reference suggesting a preferred way to …
=> Support more units and ignore case in file-size config options

.pre-commit-config.yaml, pyproject.toml
fixes #272 
Sets runtime floors on this project's dependencies:
* `click 8.0.0` ([May 2021](https://pypi.org/project/click/8.0.0/))
* `tomli 1.1.0` ([July 2021](https://pypi.org/project/tomli/1.1.0/))
Installed the oldest versions on PyPI, and ran the following:
```shell
pydistcheck --help
pydistcheck --version
pydistcheck --inspect ./tests/data/*.whl
make test-local
```
When those broke, tried newer versions.
I kept working up from there until I found versions that this project was compatible with.
=> set floors on runtime dependencies (fixes #272)

.github/ISSUE_TEMPLATE/new-check.yml, .github/workflows/static-analysis.yml, .pre-commit-config.yaml, .yamllint.yaml, Makefile, README.md, src/pydistcheck/_compat.py
Some miscellaneous development changes:
* adds `yamllint` linting
* updates all `pre-commit` hooks to their latest versions (`pre-commit autoupdate`)
* fixes GitHub Actions badges in the README
- *the `smoke-tests` one was displaying the wrong status... switched to the pattern from https://github.com/microsoft/LightGBM/pull/6570*
=> [ci] use yamllint, update pre-commit hooks

src/pydistcheck/_compat.py
Fixes #284
Replaces #285 and #286
~I decided to delete the previously made branch release/v0.8.1 as the change did not warrant an immediate release. This PR has been created in its place.~
Added the command to install the zstandard package using conda.
=> [docs] improve zstandard error message

LICENSE, MANIFEST.in, pyproject.toml, src/pydistcheck/file_utils.py
This project has a bit of code copied from https://github.com/matthew-brett/delocate, and so vendors that project's license file. I realized today that that that is not being included in wheels here (only sdists).
Looks like that's because the mechanism this project is using is `MANIFEST.in`, which isn't affecting wheels in the way this project is currently configured.
This PR proposes:
* stop using `MANIFEST.in`
* use `setuptools` `license-files` mechanism to include licenses (https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html)
=> Correctly vendor `delocate` license in wheels

.pre-commit-config.yaml, docs/how-to-test-a-python-distribution.rst
Fixes #283
* adds `validate-pyproject` to docs
* adds `cph` to docs
* clarifies in "How to Test a Python Distribution" which tools take packages as input and which take a source tree
=> [docs] add 'cph' and 'validate-pyproject' to docs (fixes #283)

docs/how-to-test-a-python-distribution.rst
#292 contained some formatting mistakes, leading to this:
ref: https://pydistcheck.readthedocs.io/en/latest/how-to-test-a-python-distribution.html
This fixes that.
=> [docs] fix formatting

.github/workflows/check-labels.yml, .github/workflows/label-checker.yml
Adds a workflow to enforce that every PR has exactly 1 of the required labels.
To ensure they're all categorized in release notes correctly, matching this:
https://github.com/jameslamb/pydistcheck/blob/127264dbfb6a68c2d2403db82e0bc5331744f61e/.github/release-drafter.yml#L4-L14
docs: https://github.com/mheap/github-action-required-labels
=> [ci] add workflow to check PR labels

docs/_static/defaults.toml, src/pydistcheck/_checks.py, src/pydistcheck/_config.py, src/pydistcheck/_inspect.py, src/pydistcheck/_utils.py, src/pydistcheck/cli.py, tests/test_cli.py, tests/test_config.py
Closes #280
Makes the units of file sizes appearing in output from `--inspect` and in log messages / errors configurable.
For example:
```shell
mkdir -p ./delete-me
pip download \
--no-deps \
-d ./delete-me \
'pandas>2.0'
```
Default behavior:
```shell
pydistcheck \
--inspect \
--max-allowed-size-compressed '500K' \
./delete-me/pandas*.whl
```
```text
checking './delete-me/pandas-2.2.3-cp312-cp312-macosx_11_0_arm64.whl'
file size
* compressed size: 10.837M
* uncompressed size: 38.545M
* compression space saving: 71.9%
contents
* directories: 154
* files: 1509 (44 compiled)
* .py - 19.428M (50.4%)
* .so - 18.699M (48.5%)
* no-extension - 0.285M (0.7%)
* .pyi - 0.101M …
```
=> make output file size units configurable

src/pydistcheck/_checks.py, tests/test_cli.py
Also removes a few unnecessary assignments in unit tests.
=> use keyword arguments in all check constructors

docs/_static/defaults.toml, src/pydistcheck/_checks.py, src/pydistcheck/_config.py, src/pydistcheck/_inspect.py, src/pydistcheck/_utils.py, src/pydistcheck/cli.py, tests/test_cli.py, tests/test_config.py, tests/test_utils.py
Closes #297
Makes the precision of file sizes appearing in output from `--inspect` and in log messages / errors configurable.
For example:
```shell
mkdir -p ./delete-me
pip download \
--no-deps \
-d ./delete-me \
'pandas>2.0'
```
Default behavior:
```shell
pydistcheck \
--inspect \
--max-allowed-size-compressed '500K' \
./delete-me/pandas*.whl
```
```text
checking './delete-me/pandas-2.2.3-cp312-cp312-macosx_11_0_arm64.whl'
file size
* compressed size: 10.837M
* uncompressed size: 38.545M
* compression space saving: 71.9%
contents
* directories: 154
* files: 1509 (44 compiled)
* .py - 19.428M (50.4%)
* .so - 18.699M (48.5%)
* no-extension - 0.285M (0.7%)
* .pyi - 0.101M …
```
=> make output file size precision configurable

pyproject.toml, src/pydistcheck/_compat.py, src/pydistcheck/_file_utils.py, src/pydistcheck/_shared_lib_utils.py
Excludes some hard-to-test codepaths from the coverage calculation, and raises the test coverage threshold.
ref: https://coverage.readthedocs.io/en/latest/excluding.html
=> exclude hard-to-test codepaths from coverage

src/pydistcheck/_shared_lib_utils.py, tests/test_shared_lib_utils.py
This PR closes #235; the "compiled-objects-have-debug-symbols" check was producing false positives for Mach-O files that have been passed through Apple's `strip`. This occurred because `strip` adds a specific weak symbol (`radr://5614542`) in Mach-O files that was detected as a debug symbol even in properly stripped binaries, even though it's just an artifact of the stripping process.
- modified the `_get_symbols` method to filter out this `radr://5614542` symbol in specific; and
- added a small test to verify the filtering behaviour.
Please refer to https://github.com/jameslamb/pydistcheck/issues/235#issuecomment-2561456586.
=> Ignore `radr://5614542` remnant debug symbol for binaries stripped via Apple's `strip` utility

.github/workflows/check-docs.yml, .gitignore, .lycheeignore, .pre-commit-config.yaml, .readthedocs.yaml, docs/_static/defaults.toml, docs/check-reference.rst, docs/conf.py, docs/how-to-test-a-python-distribution.rst, docs/installation.rst, src/pydistcheck/_config.py
fixes #293
Adds 2 types of link-checking:
1. in `sphinx` builds, for rendered docs ([via sphinx's built-in link checker](https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-the-linkcheck-builder))
2. for all files checked into source control ([with lychee](https://github.com/lycheeverse/lychee))
Saw this successfully catch some issues.
```text
[404] https://pypa.github.io/pipx/ | Network error: Not Found
```
([build link](https://github.com/jameslamb/pydistcheck/actions/runs/13802249162/job/38606655270?pr=312#step:4:98))
=> [ci] [docs] add link-checking in CI (fixes #293)

.github/workflows/smoke-tests.yml, .github/workflows/unit-tests.yml, pyproject.toml, src/pydistcheck/_checks.py, src/pydistcheck/_config.py, src/pydistcheck/_distribution_summary.py, src/pydistcheck/_file_utils.py, src/pydistcheck/_shared_lib_utils.py, src/pydistcheck/_utils.py, src/pydistcheck/cli.py, tests/data/baseballmetrics/setup.cfg
While trying to adapt to the new strong deprecation warnings from `setuptools` in #317, I found that the patterns that `setuptools` wants projects to use for license metadata requires `setuptools>=77.0`.
From https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
> _Support for [project.license-files](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license-files) and SPDX license expressions in [project.license](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license) ([PEP 639](https://peps.python.org/pep-0639/)) were introduced in version 77.0.0._
Unfortunately, that range of `setuptools` versions contains this change dropping Python 3.8 support: https://github.com/pypa/setuptools/commit/750a1891ec4a1c0602050e3463e9593a8c13aa14 …
=> drop Python 3.8 support

bin/run-smoke-tests.sh
Looks like `catboost` dropped the `.github/` directory from their sdists 🎉 
```text
checking './smoke-tests/catboost-1.2.8.tar.gz'
1. [expected-files] Did not find any directories matching pattern '*/.github'.
errors found while checking: 1
```
([build link](https://github.com/jameslamb/pydistcheck/actions/runs/14478773322/job/40610788298#step:5:1418))
=> fix smoke tests

.lycheeignore, .pre-commit-config.yaml, bin/run-smoke-tests.sh, docs/conf.py
Stack Exchange sites started returning 403s some time in the last few weeks:
```text
( check-reference: line  201) broken    https://serverfault.com/questions/9546/filename-length-limits-on-linux/9548 - 403 Client Error: Forbidden for url: https://serverfault.com/questions/9546/filename-length-limits-on-linux/9548
( check-reference: line  188) broken    https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows/22575737 - 403 Client Error: Forbidden for url: https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows/22575737
( check-reference: line  153) broken    https://superuser.com/questions/29111/what-technical-reasons-exist-for-not-using-space-characters-in-file-names - 403 Client Error: Forbidden for url: …
```
=> skip Stack Exchange sites in link checks, fix smoke tests

.pre-commit-config.yaml, src/pydistcheck/_compat.py, src/pydistcheck/_utils.py, tests/test_utils.py
Updating to the latest versions of all `pre-commit` hooks, `ruff` raised 2 new findings:
```text
src/pydistcheck/_compat.py:16:9: PLC0415 `import` should be at the top-level of a file
|
14 | def _import_zstandard() -> Any:
15 |     try:
16 |         import zstandard
|         ^^^^^^^^^^^^^^^^ PLC0415
17 |
18 |         return zstandard
|
src/pydistcheck/_utils.py:38:7: PLW1641 Object does not implement `__hash__` method
|
38 | class _FileSize:
|       ^^^^^^^^^ PLW1641
39 |     def __init__(
40 |         self,
```
This addresses the `PLW1641` recommendation and makes `_FileSize` hashable.
See:
* https://docs.astral.sh/ruff/rules/eq-without-hash/
* https://docs.python.org/3/reference/datamodel.html#object.__hash__, namely:
=> make _FileSize hashable
